//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TulsiPF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationTab
    {
        public int DonationId { get; set; }
        public Nullable<int> Donation { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public string DonationDetail { get; set; }
        public Nullable<int> MemberId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
