//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TulsiPF2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTab2
    {
        public int ImageId2 { get; set; }
        public string ImageTitle2 { get; set; }
        public string ImagePath2 { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
