//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TulsiPF2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TulsiPFEntities2 : DbContext
    {
        public TulsiPFEntities2()
            : base("name=TulsiPFEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonationTab> DonationTabs { get; set; }
        public virtual DbSet<ImageTab> ImageTabs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<SexTab> SexTabs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
